pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/MahaManisha/Move-Ticket-Booking-System-.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('movie-ticket-booking') { 
                    bat '"C:\\Program Files\\nodejs\\npm.cmd" install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('movie-ticket-booking') {
                    bat '"C:\\Program Files\\nodejs\\npm.cmd" run build'
                }
            }
        }
    }

    post {
        success {
            echo "React project built successfully!"
        }
        failure {
            echo "Build failed!"
        }
    }
}
